import * as path from 'node:path';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { BadRequestException, Injectable } from '@nestjs/common';
import { ChatMessageAttachment } from '../../sessions/types/chat-message-attachment';
import { PromptImageFile } from '../../sessions/types/prompt-image-file';
import { GeneratedPrototypeFile } from '../types/generated-prototype-files';

@Injectable()
export class PrototypeFilesystemService {
  async ensureSessionDirectory(
    prototypeRoot: string,
    sessionSlug: string,
  ): Promise<string> {
    const sessionDirectory = path.join(prototypeRoot, sessionSlug);

    await mkdir(sessionDirectory, { recursive: true });

    return sessionDirectory;
  }

  async createCurrentPrototype(
    sessionDirectory: string,
    filesOrPrompt: GeneratedPrototypeFile[] | string,
  ): Promise<string> {
    const currentDirectory = path.join(sessionDirectory, 'current');

    await mkdir(currentDirectory, { recursive: true });

    if (typeof filesOrPrompt === 'string') {
      await writeFile(
        path.join(currentDirectory, 'README.md'),
        this.createMockContent('current', filesOrPrompt),
        'utf8',
      );
    } else {
      await this.writeGeneratedFiles(currentDirectory, filesOrPrompt);
    }

    return currentDirectory;
  }

  async copyCurrentToNew(sessionDirectory: string): Promise<string> {
    const currentDirectory = path.join(sessionDirectory, 'current');
    const newDirectory = path.join(sessionDirectory, 'new');

    await rm(newDirectory, { recursive: true, force: true });
    await cp(currentDirectory, newDirectory, { recursive: true });

    return newDirectory;
  }

  async writeNewPromptPatch(
    sessionDirectory: string,
    filesOrPrompt: GeneratedPrototypeFile[] | string,
  ): Promise<string> {
    const newDirectory = path.join(sessionDirectory, 'new');

    if (typeof filesOrPrompt !== 'string') {
      await this.writeGeneratedFiles(newDirectory, filesOrPrompt);

      return newDirectory;
    }

    const promptFile = path.join(newDirectory, '_prompt.md');

    await writeFile(
      promptFile,
      this.createMockContent('new', filesOrPrompt),
      'utf8',
    );

    return promptFile;
  }

  async savePromptImages(
    sessionDirectory: string,
    files: PromptImageFile[] = [],
  ): Promise<ChatMessageAttachment[]> {
    if (files.length === 0) {
      return [];
    }

    const uploadsDirectory = path.join(sessionDirectory, '_uploads');

    await mkdir(uploadsDirectory, { recursive: true });

    return Promise.all(
      files.map(async (file, index) => {
        if (!file.mimetype.startsWith('image/')) {
          throw new BadRequestException('Only image uploads are supported');
        }

        const filename = `${Date.now()}-${index}-${this.sanitizeFilename(
          file.originalname,
        )}`;
        const targetFilePath = path.join(uploadsDirectory, filename);

        await writeFile(targetFilePath, file.buffer);

        return {
          type: 'image',
          filename,
          mimeType: file.mimetype,
          path: targetFilePath,
          size: file.size,
        };
      }),
    );
  }

  async readAttachmentAsDataUrl(
    attachment: ChatMessageAttachment,
  ): Promise<string> {
    const content = await readFile(attachment.path);

    return `data:${attachment.mimeType};base64,${content.toString('base64')}`;
  }

  async writeGeneratedFiles(
    targetDirectory: string,
    files: GeneratedPrototypeFile[],
  ): Promise<void> {
    await Promise.all(
      files.map(async (file) => {
        const targetFilePath = this.resolveSafeTargetPath(
          targetDirectory,
          file.path,
        );

        await mkdir(path.dirname(targetFilePath), { recursive: true });
        await writeFile(targetFilePath, file.content, 'utf8');
      }),
    );
  }

  private resolveSafeTargetPath(
    targetDirectory: string,
    relativeFilePath: string,
  ): string {
    if (path.isAbsolute(relativeFilePath)) {
      throw new BadRequestException('Generated file path must be relative');
    }

    const targetFilePath = path.resolve(targetDirectory, relativeFilePath);
    const targetRoot = path.resolve(targetDirectory);

    if (
      targetFilePath !== targetRoot &&
      !targetFilePath.startsWith(`${targetRoot}${path.sep}`)
    ) {
      throw new BadRequestException(
        'Generated file path escapes target folder',
      );
    }

    return targetFilePath;
  }

  private createMockContent(kind: 'current' | 'new', prompt: string): string {
    return [
      `# ${kind} prototype`,
      '',
      'Mock file generated by backend demo.',
      '',
      'Prompt:',
      prompt,
      '',
    ].join('\n');
  }

  private sanitizeFilename(filename: string): string {
    const parsedPath = path.parse(filename);
    const extension = parsedPath.ext.replace(/[^a-zA-Z0-9.]/g, '');
    const name = parsedPath.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');

    return `${name || 'image'}${extension}`;
  }
}
